/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "cache_items_constants.h"

namespace agora { namespace cache {

const cache_itemsConstants g_cache_items_constants;

cache_itemsConstants::cache_itemsConstants() {
}

}} // namespace

