/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef cache_items_CONSTANTS_H
#define cache_items_CONSTANTS_H

#include "cache_items_types.h"

namespace agora { namespace cache {

class cache_itemsConstants {
 public:
  cache_itemsConstants();

};

extern const cache_itemsConstants g_cache_items_constants;

}} // namespace

#endif
