/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef sei_info_CONSTANTS_H
#define sei_info_CONSTANTS_H

#include "sei_info_types.h"

namespace agora { namespace rtc { namespace sei {

class sei_infoConstants {
 public:
  sei_infoConstants();

};

extern const sei_infoConstants g_sei_info_constants;

}}} // namespace

#endif
