/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "sei_info_constants.h"

namespace agora { namespace rtc { namespace sei {

const sei_infoConstants g_sei_info_constants;

sei_infoConstants::sei_infoConstants() {
}

}}} // namespace

