/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef vosdk_report_items_CONSTANTS_H
#define vosdk_report_items_CONSTANTS_H

#include "vosdk_report_items_types.h"

namespace io { namespace agora { namespace argus {

class vosdk_report_itemsConstants {
 public:
  vosdk_report_itemsConstants();

};

extern const vosdk_report_itemsConstants g_vosdk_report_items_constants;

}}} // namespace

#endif
