/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "vosdk_report_items_constants.h"

namespace io { namespace agora { namespace argus {

const vosdk_report_itemsConstants g_vosdk_report_items_constants;

vosdk_report_itemsConstants::vosdk_report_itemsConstants() {
}

}}} // namespace

