/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: cache_items.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "cache_items.pb-c.h"
void io__agora__pb__cache__cache_document__init(Io__Agora__Pb__Cache__CacheDocument *message) {
  static const Io__Agora__Pb__Cache__CacheDocument init_value =
      IO__AGORA__PB__CACHE__CACHE_DOCUMENT__INIT;
  *message = init_value;
}
size_t io__agora__pb__cache__cache_document__get_packed_size(
    const Io__Agora__Pb__Cache__CacheDocument *message) {
  assert(message->base.descriptor == &io__agora__pb__cache__cache_document__descriptor);
  return protobuf_c_message_get_packed_size((const ProtobufCMessage *)(message));
}
size_t io__agora__pb__cache__cache_document__pack(
    const Io__Agora__Pb__Cache__CacheDocument *message, uint8_t *out) {
  assert(message->base.descriptor == &io__agora__pb__cache__cache_document__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t io__agora__pb__cache__cache_document__pack_to_buffer(
    const Io__Agora__Pb__Cache__CacheDocument *message, ProtobufCBuffer *buffer) {
  assert(message->base.descriptor == &io__agora__pb__cache__cache_document__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message, buffer);
}
Io__Agora__Pb__Cache__CacheDocument *io__agora__pb__cache__cache_document__unpack(
    ProtobufCAllocator *allocator, size_t len, const uint8_t *data) {
  return (Io__Agora__Pb__Cache__CacheDocument *)protobuf_c_message_unpack(
      &io__agora__pb__cache__cache_document__descriptor, allocator, len, data);
}
void io__agora__pb__cache__cache_document__free_unpacked(
    Io__Agora__Pb__Cache__CacheDocument *message, ProtobufCAllocator *allocator) {
  if (!message) return;
  assert(message->base.descriptor == &io__agora__pb__cache__cache_document__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
void io__agora__pb__cache__report_cache_document__init(
    Io__Agora__Pb__Cache__ReportCacheDocument *message) {
  static const Io__Agora__Pb__Cache__ReportCacheDocument init_value =
      IO__AGORA__PB__CACHE__REPORT_CACHE_DOCUMENT__INIT;
  *message = init_value;
}
size_t io__agora__pb__cache__report_cache_document__get_packed_size(
    const Io__Agora__Pb__Cache__ReportCacheDocument *message) {
  assert(message->base.descriptor == &io__agora__pb__cache__report_cache_document__descriptor);
  return protobuf_c_message_get_packed_size((const ProtobufCMessage *)(message));
}
size_t io__agora__pb__cache__report_cache_document__pack(
    const Io__Agora__Pb__Cache__ReportCacheDocument *message, uint8_t *out) {
  assert(message->base.descriptor == &io__agora__pb__cache__report_cache_document__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t io__agora__pb__cache__report_cache_document__pack_to_buffer(
    const Io__Agora__Pb__Cache__ReportCacheDocument *message, ProtobufCBuffer *buffer) {
  assert(message->base.descriptor == &io__agora__pb__cache__report_cache_document__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message, buffer);
}
Io__Agora__Pb__Cache__ReportCacheDocument *io__agora__pb__cache__report_cache_document__unpack(
    ProtobufCAllocator *allocator, size_t len, const uint8_t *data) {
  return (Io__Agora__Pb__Cache__ReportCacheDocument *)protobuf_c_message_unpack(
      &io__agora__pb__cache__report_cache_document__descriptor, allocator, len, data);
}
void io__agora__pb__cache__report_cache_document__free_unpacked(
    Io__Agora__Pb__Cache__ReportCacheDocument *message, ProtobufCAllocator *allocator) {
  if (!message) return;
  assert(message->base.descriptor == &io__agora__pb__cache__report_cache_document__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
static const ProtobufCFieldDescriptor io__agora__pb__cache__cache_document__field_descriptors[10] =
    {
        {
            "dnsList", 1, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_BYTES, 0, /* quantifier_offset */
            offsetof(Io__Agora__Pb__Cache__CacheDocument, dnslist), NULL, NULL, 0, /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "lastSid", 2, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_STRING, 0, /* quantifier_offset */
            offsetof(Io__Agora__Pb__Cache__CacheDocument, lastsid), NULL, &protobuf_c_empty_string,
            0,            /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "failedSid", 3, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_STRING,
            0, /* quantifier_offset */
            offsetof(Io__Agora__Pb__Cache__CacheDocument, failedsid), NULL,
            &protobuf_c_empty_string, 0, /* flags */
            0, NULL, NULL                /* reserved1,reserved2, etc */
        },
        {
            "policy", 4, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_BYTES, 0, /* quantifier_offset */
            offsetof(Io__Agora__Pb__Cache__CacheDocument, policy), NULL, NULL, 0, /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "installId", 5, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_STRING,
            0, /* quantifier_offset */
            offsetof(Io__Agora__Pb__Cache__CacheDocument, installid), NULL,
            &protobuf_c_empty_string, 0, /* flags */
            0, NULL, NULL                /* reserved1,reserved2, etc */
        },
        {
            "netEngine", 6, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_INT32, 0, /* quantifier_offset */
            offsetof(Io__Agora__Pb__Cache__CacheDocument, netengine), NULL, NULL, 0, /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "agoraUniqueId", 7, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_STRING,
            0, /* quantifier_offset */
            offsetof(Io__Agora__Pb__Cache__CacheDocument, agorauniqueid), NULL,
            &protobuf_c_empty_string, 0, /* flags */
            0, NULL, NULL                /* reserved1,reserved2, etc */
        },
        {
            "logUploadedList", 8, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_BYTES,
            0, /* quantifier_offset */
            offsetof(Io__Agora__Pb__Cache__CacheDocument, loguploadedlist), NULL, NULL,
            0,            /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "udid", 9, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_STRING, 0, /* quantifier_offset */
            offsetof(Io__Agora__Pb__Cache__CacheDocument, udid), NULL, &protobuf_c_empty_string,
            0,            /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "storeParams", 10, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_BYTES,
            0, /* quantifier_offset */
            offsetof(Io__Agora__Pb__Cache__CacheDocument, storeparams), NULL, NULL, 0, /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
};
static const unsigned io__agora__pb__cache__cache_document__field_indices_by_name[] = {
    6, /* field[6] = agoraUniqueId */
    0, /* field[0] = dnsList */
    2, /* field[2] = failedSid */
    4, /* field[4] = installId */
    1, /* field[1] = lastSid */
    7, /* field[7] = logUploadedList */
    5, /* field[5] = netEngine */
    3, /* field[3] = policy */
    9, /* field[9] = storeParams */
    8, /* field[8] = udid */
};
static const ProtobufCIntRange io__agora__pb__cache__cache_document__number_ranges[1 + 1] = {
    {1, 0}, {0, 10}};
const ProtobufCMessageDescriptor io__agora__pb__cache__cache_document__descriptor = {
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "io.agora.pb.cache.CacheDocument",
    "CacheDocument",
    "Io__Agora__Pb__Cache__CacheDocument",
    "io.agora.pb.cache",
    sizeof(Io__Agora__Pb__Cache__CacheDocument),
    10,
    io__agora__pb__cache__cache_document__field_descriptors,
    io__agora__pb__cache__cache_document__field_indices_by_name,
    1,
    io__agora__pb__cache__cache_document__number_ranges,
    (ProtobufCMessageInit)io__agora__pb__cache__cache_document__init,
    NULL,
    NULL,
    NULL /* reserved[123] */
};
static const ProtobufCFieldDescriptor
    io__agora__pb__cache__report_cache_document__field_descriptors[1] = {
        {
            "reportCacheList", 1, PROTOBUF_C_LABEL_REPEATED, PROTOBUF_C_TYPE_BYTES,
            offsetof(Io__Agora__Pb__Cache__ReportCacheDocument, n_reportcachelist),
            offsetof(Io__Agora__Pb__Cache__ReportCacheDocument, reportcachelist), NULL, NULL,
            0,            /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
};
static const unsigned io__agora__pb__cache__report_cache_document__field_indices_by_name[] = {
    0, /* field[0] = reportCacheList */
};
static const ProtobufCIntRange io__agora__pb__cache__report_cache_document__number_ranges[1 + 1] = {
    {1, 0}, {0, 1}};
const ProtobufCMessageDescriptor io__agora__pb__cache__report_cache_document__descriptor = {
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "io.agora.pb.cache.ReportCacheDocument",
    "ReportCacheDocument",
    "Io__Agora__Pb__Cache__ReportCacheDocument",
    "io.agora.pb.cache",
    sizeof(Io__Agora__Pb__Cache__ReportCacheDocument),
    1,
    io__agora__pb__cache__report_cache_document__field_descriptors,
    io__agora__pb__cache__report_cache_document__field_indices_by_name,
    1,
    io__agora__pb__cache__report_cache_document__number_ranges,
    (ProtobufCMessageInit)io__agora__pb__cache__report_cache_document__init,
    NULL,
    NULL,
    NULL /* reserved[123] */
};
