/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: counter.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "counter.pb-c.h"
void io__agora__pb__counter__counter__init(Io__Agora__Pb__Counter__Counter *message) {
  static const Io__Agora__Pb__Counter__Counter init_value = IO__AGORA__PB__COUNTER__COUNTER__INIT;
  *message = init_value;
}
size_t io__agora__pb__counter__counter__get_packed_size(
    const Io__Agora__Pb__Counter__Counter *message) {
  assert(message->base.descriptor == &io__agora__pb__counter__counter__descriptor);
  return protobuf_c_message_get_packed_size((const ProtobufCMessage *)(message));
}
size_t io__agora__pb__counter__counter__pack(const Io__Agora__Pb__Counter__Counter *message,
                                             uint8_t *out) {
  assert(message->base.descriptor == &io__agora__pb__counter__counter__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t io__agora__pb__counter__counter__pack_to_buffer(
    const Io__Agora__Pb__Counter__Counter *message, ProtobufCBuffer *buffer) {
  assert(message->base.descriptor == &io__agora__pb__counter__counter__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message, buffer);
}
Io__Agora__Pb__Counter__Counter *io__agora__pb__counter__counter__unpack(
    ProtobufCAllocator *allocator, size_t len, const uint8_t *data) {
  return (Io__Agora__Pb__Counter__Counter *)protobuf_c_message_unpack(
      &io__agora__pb__counter__counter__descriptor, allocator, len, data);
}
void io__agora__pb__counter__counter__free_unpacked(Io__Agora__Pb__Counter__Counter *message,
                                                    ProtobufCAllocator *allocator) {
  if (!message) return;
  assert(message->base.descriptor == &io__agora__pb__counter__counter__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
void io__agora__pb__counter__counter_item__init(Io__Agora__Pb__Counter__CounterItem *message) {
  static const Io__Agora__Pb__Counter__CounterItem init_value =
      IO__AGORA__PB__COUNTER__COUNTER_ITEM__INIT;
  *message = init_value;
}
size_t io__agora__pb__counter__counter_item__get_packed_size(
    const Io__Agora__Pb__Counter__CounterItem *message) {
  assert(message->base.descriptor == &io__agora__pb__counter__counter_item__descriptor);
  return protobuf_c_message_get_packed_size((const ProtobufCMessage *)(message));
}
size_t io__agora__pb__counter__counter_item__pack(
    const Io__Agora__Pb__Counter__CounterItem *message, uint8_t *out) {
  assert(message->base.descriptor == &io__agora__pb__counter__counter_item__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t io__agora__pb__counter__counter_item__pack_to_buffer(
    const Io__Agora__Pb__Counter__CounterItem *message, ProtobufCBuffer *buffer) {
  assert(message->base.descriptor == &io__agora__pb__counter__counter_item__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message, buffer);
}
Io__Agora__Pb__Counter__CounterItem *io__agora__pb__counter__counter_item__unpack(
    ProtobufCAllocator *allocator, size_t len, const uint8_t *data) {
  return (Io__Agora__Pb__Counter__CounterItem *)protobuf_c_message_unpack(
      &io__agora__pb__counter__counter_item__descriptor, allocator, len, data);
}
void io__agora__pb__counter__counter_item__free_unpacked(
    Io__Agora__Pb__Counter__CounterItem *message, ProtobufCAllocator *allocator) {
  if (!message) return;
  assert(message->base.descriptor == &io__agora__pb__counter__counter_item__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
static const ProtobufCFieldDescriptor io__agora__pb__counter__counter__field_descriptors[3] = {
    {
        "sid", 1, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_STRING, 0, /* quantifier_offset */
        offsetof(Io__Agora__Pb__Counter__Counter, sid), NULL, &protobuf_c_empty_string,
        0,            /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
    {
        "peer", 2, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_INT64, 0,     /* quantifier_offset */
        offsetof(Io__Agora__Pb__Counter__Counter, peer), NULL, NULL, 0, /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
    {
        "items", 3, PROTOBUF_C_LABEL_REPEATED, PROTOBUF_C_TYPE_MESSAGE,
        offsetof(Io__Agora__Pb__Counter__Counter, n_items),
        offsetof(Io__Agora__Pb__Counter__Counter, items),
        &io__agora__pb__counter__counter_item__descriptor, NULL, 0, /* flags */
        0, NULL, NULL                                               /* reserved1,reserved2, etc */
    },
};
static const unsigned io__agora__pb__counter__counter__field_indices_by_name[] = {
    2, /* field[2] = items */
    1, /* field[1] = peer */
    0, /* field[0] = sid */
};
static const ProtobufCIntRange io__agora__pb__counter__counter__number_ranges[1 + 1] = {{1, 0},
                                                                                        {0, 3}};
const ProtobufCMessageDescriptor io__agora__pb__counter__counter__descriptor = {
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "io.agora.pb.counter.Counter",
    "Counter",
    "Io__Agora__Pb__Counter__Counter",
    "io.agora.pb.counter",
    sizeof(Io__Agora__Pb__Counter__Counter),
    3,
    io__agora__pb__counter__counter__field_descriptors,
    io__agora__pb__counter__counter__field_indices_by_name,
    1,
    io__agora__pb__counter__counter__number_ranges,
    (ProtobufCMessageInit)io__agora__pb__counter__counter__init,
    NULL,
    NULL,
    NULL /* reserved[123] */
};
static const ProtobufCFieldDescriptor io__agora__pb__counter__counter_item__field_descriptors[5] = {
    {
        "lts", 1, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_INT64, 0,         /* quantifier_offset */
        offsetof(Io__Agora__Pb__Counter__CounterItem, lts), NULL, NULL, 0, /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
    {
        "id", 2, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_INT32, 0,         /* quantifier_offset */
        offsetof(Io__Agora__Pb__Counter__CounterItem, id), NULL, NULL, 0, /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
    {
        "value", 3, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_INT32, 0,         /* quantifier_offset */
        offsetof(Io__Agora__Pb__Counter__CounterItem, value), NULL, NULL, 0, /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
    {
        "tagErrorCode", 4, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_INT32, 0, /* quantifier_offset */
        offsetof(Io__Agora__Pb__Counter__CounterItem, tagerrorcode), NULL, NULL, 0, /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
    {
        "streamId", 5, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT32, 0, /* quantifier_offset */
        offsetof(Io__Agora__Pb__Counter__CounterItem, streamid), NULL, NULL, 0, /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
};
static const unsigned io__agora__pb__counter__counter_item__field_indices_by_name[] = {
    1, /* field[1] = id */
    0, /* field[0] = lts */
    4, /* field[4] = streamId */
    3, /* field[3] = tagErrorCode */
    2, /* field[2] = value */
};
static const ProtobufCIntRange io__agora__pb__counter__counter_item__number_ranges[1 + 1] = {
    {1, 0}, {0, 5}};
const ProtobufCMessageDescriptor io__agora__pb__counter__counter_item__descriptor = {
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "io.agora.pb.counter.CounterItem",
    "CounterItem",
    "Io__Agora__Pb__Counter__CounterItem",
    "io.agora.pb.counter",
    sizeof(Io__Agora__Pb__Counter__CounterItem),
    5,
    io__agora__pb__counter__counter_item__field_descriptors,
    io__agora__pb__counter__counter_item__field_indices_by_name,
    1,
    io__agora__pb__counter__counter_item__number_ranges,
    (ProtobufCMessageInit)io__agora__pb__counter__counter_item__init,
    NULL,
    NULL,
    NULL /* reserved[123] */
};
