/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: message.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "message.pb-c.h"
void io__agora__pb__message__message__init(Io__Agora__Pb__Message__Message *message) {
  static const Io__Agora__Pb__Message__Message init_value = IO__AGORA__PB__MESSAGE__MESSAGE__INIT;
  *message = init_value;
}
size_t io__agora__pb__message__message__get_packed_size(
    const Io__Agora__Pb__Message__Message *message) {
  assert(message->base.descriptor == &io__agora__pb__message__message__descriptor);
  return protobuf_c_message_get_packed_size((const ProtobufCMessage *)(message));
}
size_t io__agora__pb__message__message__pack(const Io__Agora__Pb__Message__Message *message,
                                             uint8_t *out) {
  assert(message->base.descriptor == &io__agora__pb__message__message__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t io__agora__pb__message__message__pack_to_buffer(
    const Io__Agora__Pb__Message__Message *message, ProtobufCBuffer *buffer) {
  assert(message->base.descriptor == &io__agora__pb__message__message__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message, buffer);
}
Io__Agora__Pb__Message__Message *io__agora__pb__message__message__unpack(
    ProtobufCAllocator *allocator, size_t len, const uint8_t *data) {
  return (Io__Agora__Pb__Message__Message *)protobuf_c_message_unpack(
      &io__agora__pb__message__message__descriptor, allocator, len, data);
}
void io__agora__pb__message__message__free_unpacked(Io__Agora__Pb__Message__Message *message,
                                                    ProtobufCAllocator *allocator) {
  if (!message) return;
  assert(message->base.descriptor == &io__agora__pb__message__message__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
static const ProtobufCFieldDescriptor io__agora__pb__message__message__field_descriptors[2] = {
    {
        "id", 1, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_INT32, 0,     /* quantifier_offset */
        offsetof(Io__Agora__Pb__Message__Message, id), NULL, NULL, 0, /* flags */
        0, NULL, NULL                                                 /* reserved1,reserved2, etc */
    },
    {
        "msg", 2, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_BYTES, 0,     /* quantifier_offset */
        offsetof(Io__Agora__Pb__Message__Message, msg), NULL, NULL, 0, /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
};
static const unsigned io__agora__pb__message__message__field_indices_by_name[] = {
    0, /* field[0] = id */
    1, /* field[1] = msg */
};
static const ProtobufCIntRange io__agora__pb__message__message__number_ranges[1 + 1] = {{1, 0},
                                                                                        {0, 2}};
const ProtobufCMessageDescriptor io__agora__pb__message__message__descriptor = {
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "io.agora.pb.message.Message",
    "Message",
    "Io__Agora__Pb__Message__Message",
    "io.agora.pb.message",
    sizeof(Io__Agora__Pb__Message__Message),
    2,
    io__agora__pb__message__message__field_descriptors,
    io__agora__pb__message__message__field_indices_by_name,
    1,
    io__agora__pb__message__message__number_ranges,
    (ProtobufCMessageInit)io__agora__pb__message__message__init,
    NULL,
    NULL,
    NULL /* reserved[123] */
};
