/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: message.proto */

#ifndef PROTOBUF_C_message_2eproto__INCLUDED
#define PROTOBUF_C_message_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

typedef struct _Io__Agora__Pb__Message__Message Io__Agora__Pb__Message__Message;

/* --- enums --- */

/* --- messages --- */

struct _Io__Agora__Pb__Message__Message {
  ProtobufCMessage base;
  int32_t id;
  ProtobufCBinaryData msg;
};
#define IO__AGORA__PB__MESSAGE__MESSAGE__INIT                             \
  {                                                                       \
    PROTOBUF_C_MESSAGE_INIT(&io__agora__pb__message__message__descriptor) \
    , 0, { 0, NULL }                                                      \
  }

/* Io__Agora__Pb__Message__Message methods */
void io__agora__pb__message__message__init(Io__Agora__Pb__Message__Message *message);
size_t io__agora__pb__message__message__get_packed_size(
    const Io__Agora__Pb__Message__Message *message);
size_t io__agora__pb__message__message__pack(const Io__Agora__Pb__Message__Message *message,
                                             uint8_t *out);
size_t io__agora__pb__message__message__pack_to_buffer(
    const Io__Agora__Pb__Message__Message *message, ProtobufCBuffer *buffer);
Io__Agora__Pb__Message__Message *io__agora__pb__message__message__unpack(
    ProtobufCAllocator *allocator, size_t len, const uint8_t *data);
void io__agora__pb__message__message__free_unpacked(Io__Agora__Pb__Message__Message *message,
                                                    ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Io__Agora__Pb__Message__Message_Closure)(
    const Io__Agora__Pb__Message__Message *message, void *closure_data);

/* --- services --- */

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor io__agora__pb__message__message__descriptor;

PROTOBUF_C__END_DECLS

#endif /* PROTOBUF_C_message_2eproto__INCLUDED */
